[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*

[coverage:run]
source = src
omit =
    */tests/*
    */__init__.py

[coverage:report]
show_missing = True
skip_empty = True
